fix: sdk file deletion

diff --git a/.github/workflows/build-and-realease.yml b/.github/workflows/build-and-realease.yml
--- a/.github/workflows/build-and-realease.yml
+++ b/.github/workflows/build-and-realease.yml
@@ -135,6 +135,18 @@ jobs:
       - name: Prepare Build Environment
         run: |
           cd "$CACHE_DIR_SDK"
+          if ! ( wget -q -O - "$SDK_URL_PATH/sha256sums" | grep -- "$SDK_NAME" > sha256sums.small 2>/dev/null ) ; then
+            echo "::error::Can not find ${SDK_NAME} file in sha256sums."
+            exit 1
+          fi
+          SDK_FILE="$(cat sha256sums.small | cut -d' ' -f2 | sed 's/*//g')"
+          if ! sha256sum -c ./sha256sums.small >/dev/null 2>&1 ; then
+            wget -q -O "$SDK_FILE" "$SDK_URL_PATH/$SDK_FILE"
+            if ! sha256sum -c ./sha256sums.small >/dev/null 2>&1 ; then
+              echo "::error::SDK can not be verified!"
+              exit 1
+            fi
+          fi
           wget -q -O "$SDK_FILE" "$SDK_URL_PATH/$SDK_FILE"
           tar -Jxf "$CACHE_DIR_SDK/$SDK_FILE" -C "$SDK_HOME" --strip=1
           cd "$SDK_HOME"
